In [2]:
import pandas as pd
from sqlalchemy import create_engine
import psycopg2
from sqlalchemy import inspect
import snowflake.connector
from snowflake.connector.pandas_tools import write_pandas

In [3]:
source_engine = create_engine("postgresql+psycopg2://postgres:QztLWcoQoMcFPKoKgCyuDwUPjOHUYdtO@trolley.proxy.rlwy.net:50067/railway")

In [4]:
categories_df = pd.read_sql(f" select * from public.categories", source_engine)

In [5]:
categories_df.tail(5)

,id,name,slug,is_active,created_at,updated_at
0,1,Electronics,electronics,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,2,Clothing,clothing,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
2,3,Books,books,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
3,4,Home & Kitchen,home-kitchen,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
4,5,Sports,sports,True,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00

In [6]:
inspector = inspect(source_engine)
table_list = inspector.get_table_names()
print( table_list)

['categories', 'products', 'customers', 'orders', 'coupons', 'order_items', 'payments', 'shipping', 'inventory', 'reviews']

In [7]:
dfs_dict = {}

for table in table_list:
    dfs_dict[table] = pd.read_sql(f"SELECT * FROM {table}", source_engine)

In [8]:
coupons_df = dfs_dict["coupons"]

In [9]:
coupons_df.head(5)

,id,code,discount_pct,max_uses,used_count,is_active,expires_at,created_at,updated_at
0,3,FLASH50,50.0,50,0,True,None,2026-03-11 02:31:45.075615+00:00,2026-03-11 02:31:45.075615+00:00
1,2,SAVE20,20.0,100,1,True,None,2026-03-11 02:31:45.075615+00:00,2026-03-11 13:30:44.214771+00:00
2,1,WELCOME10,10.0,500,2,True,None,2026-03-11 02:31:45.075615+00:00,2026-03-20 04:38:32.278907+00:00

In [10]:
#Snowflake connection parameters
conn = snowflake.connector.connect(
    user='TIWATOPEIYIOHA',
    password='Pejusokunle1992',
    account='TTZIGDX-PH57042',  # e.g., 'abcd1234.us-east-1'
    warehouse='COMPUTE_WH',
    database='DATABASE3',
    schema='BRONZE'
)
print("connection successful")

connection successful

In [77]:
cursor = conn.cursor()

In [11]:

dfs_dict = {}

for table_name in table_list:
    dfs_dict[table_name] = pd.read_sql(
        f"SELECT * FROM public.{table_name}",
        source_engine
    )

def load_to_snowflake(conn, dfs_dict, database, schema):
    for table_name, df in dfs_dict.items():
        success, nchunks, nrows, _ = write_pandas(
            conn=conn,
            df=df,
            table_name=table_name.upper(),
            auto_create_table=True,
            database=database,
            schema=schema
        )
        print(f"{table_name}: success={success}, rows={nrows}, chunks={nchunks}")

In [12]:
load_to_snowflake(conn, dfs_dict, "DATABASE3", "BRONZE")

C:\Users\userlab\AppData\Local\Temp\ipykernel_19332\3905318709.py:15: UserWarning: Dataframe contains a datetime with timezone column, but 'use_logical_type=None'. This can result in datetimes being incorrectly written to Snowflake. Consider setting 'use_logical_type = True'
  success, nchunks, nrows, _ = write_pandas(

categories: success=True, rows=5, chunks=1
products: success=True, rows=15, chunks=1
customers: success=True, rows=128, chunks=1
orders: success=True, rows=567, chunks=1
coupons: success=True, rows=3, chunks=1
order_items: success=True, rows=1679, chunks=1
payments: success=True, rows=567, chunks=1
shipping: success=True, rows=567, chunks=1
inventory: success=True, rows=15, chunks=1
reviews: success=True, rows=225, chunks=1